server:
  port: 7090
  servlet:
    context-path: /api
    session:
      timeout: PT60M

spring:

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${TYP_DB_HOST}:${TYP_MYSQL_PORT}/${TYP_DB_NAME}
    username: ${TYP_DB_USER}
    password: ${TYP_DB_PASSWORD}
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    database: 0
    host: ${TYP_DB_HOST}
    port: ${TYP_REDIS_PORT}
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    connect-timeout: 2000

  mail:
    host: smtp.qq.com
    username: ${TYP_QQ_EMAIL}
    password: ${TYP_QQ_EMAIL_CODE}
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true



project:
  folder: D:/code/Java/TaYangPan

log:
  root:
    level: debug

admin:
  emails: 1194346674@qq.com

dev: false

